#******************************************************************************
#  Nome:   Bruno Rafael Arico         			8125459
#          Nicolas Nogueira Lopes da Silva   	9277541
#
#*****************************************************************************/

CFLAGS = -g -Wall -pthread

default : EP2

EP2 :EP2.o 
	$(CC) $(CFLAGS) EP2.o -o ep2
